services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports:
      - "4001:8080"
    volumes:
      - ./swagger:/docs:ro
    environment:
      SWAGGER_JSON: /docs/openapi.yaml
