services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports:
      - "4001:8080"
    environment:
      SWAGGER_JSON: /docs/openapi.yaml
    volumes:
      - /data/compose/swagger_docker/swagger:/docs:ro
