openapi: 3.0.0
info:
  title: Frank's Docker API
  version: 1.0.0

servers:
  - url: http://unraid.local:3001  # oder z. B. http://backend:3000 im Compose-Netzwerk

paths:
  /ping:
    get:
      summary: Testverbindung zum Container
      responses:
        '200':
          description: OK, der Container lebt.
