openapi: 3.0.0
info:
  title: Frank's Docker API
  description: Swagger-Doku für dein Node.js-Backend
  version: 1.0.0

servers:
  - url: http://unraid.local:3001
    description: Lokales Node-Backend

paths:
  /ping:
    get:
      summary: Testverbindung zum Container
      description: Prüft, ob dein Backend erreichbar ist.
      responses:
        '200':
          description: OK – Backend lebt
          content:
            application/json:
              schema:
                type: object
                properties:
                  alive:
                    type: boolean
                    example: true
