openapi: 3.0.0
info:
  title: Frank's Docker API
  version: 1.0.0

servers:
  - url: http://unraid.local:3001

paths:
  /ping:
    get:
      summary: Testverbindung zum Container
      responses:
        '200':
          description: OK, der Container lebt.
          content:
            application/json:
              schema:
                type: object
                properties:
                  alive:
                    type: boolean
                    example: true
